version: '3'
services:
  id4namespace-service:
    image: id4namespace
    ports:
      - "8080:8080"
    environment:
      APP_GENERATOR: uuid
  id4namespace-app:
    image: id4namespace-app
    depends_on:
      - id4namespace-service
    ports:
      - "80:80"
