version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - "27019:27017"

  id4namespace-service:
    image: id4namespace
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/id4namespace
